# Generated by Django 3.2 on 2022-04-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_places_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='contribution',
            field=models.IntegerField(default=0),
        ),
    ]
